CarWebApp/Entities/Car.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CarWebApp.Entities
{
    public class Car
    {
        public int Id { get; set; }

        [Required]
        [DisplayName("Registration Number")]
        [StringLength(maximumLength: 7, MinimumLength = 7, ErrorMessage = "Registration number must have 7 characters.")]
        public string RegistrationNumber { get; set; }
        
        [Required]
        [StringLength(maximumLength: 17, MinimumLength = 17, ErrorMessage = "VIN must have 17 characters.")] 
        [DisplayName("VIN")] 
        public string VIN { get; set; }

        public virtual CarModel CarModel { get; set; }
        [DisplayName("Car Model")]
        public int CarModelId { get; set; }
    }
}

CarWebApp/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarWebApp.Entities;
using CarWebApp.Exceptions;
using CarWebApp.Models;
using CarWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;


namespace CarWebApp.Controllers
{
    [ApiController]
    [Route("[controller]/[action]")]
    public class CarController : Controller
    {
        private readonly ICarService _carService;
        private readonly ICarModelService _carModelService;
        private readonly IUserService _userService;

        public CarController(ICarService carService, ICarModelService carModelService, IUserService userService)
        {
            _carService = carService;
            _carModelService = carModelService;
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> List([FromQuery]int? carBrandFilerId)
        {
            var cars = await _carService.GetAll();

            if (carBrandFilerId != null)
            {
                cars = cars.Where(x => x.CarModel.CarBrand.Id == carBrandFilerId).ToList();
            }
            
            ViewBag.CarBrands = (await _carModelService.GetAll())
                .Select(x => x.CarBrand)
                .Distinct()
                .Select(x => new SelectListItem(x.Name, x.Id.ToString()))
                .ToList();
            
            return View(new CarListModel()
            {
                Cars = cars,
                CarBrandFilerId = carBrandFilerId
            });
        }
        
        [HttpGet]
        public async Task<IActionResult> Print([FromQuery]int? carBrandFilerId)
        {
            var model = await _carService.GetAll();

            if (carBrandFilerId != null)
            {
                model = model.Where(x => x.CarModel.CarBrand.Id == carBrandFilerId).ToList();
            }
            
            var pdf = new ViewAsPdf("PrintList", model);
            return pdf;
        }
        
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var comboBoxList = await _carModelService.GetCarModelSelectList();
            ViewBag.CarModelId = comboBoxList;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] Car model)
        {
            await _carService.Add(model);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit([FromQuery]int id)
        {
            var comboBoxList = await _carModelService.GetCarModelSelectList();
            ViewBag.CarModelId = comboBoxList;

            var entity = await _carService.Get(id);
            
            return View(entity);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] Car model)
        {
            await _carService.Edit(model);
            
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public async Task<IActionResult> DeleteConfirm([FromQuery] int id)
        {
            return View( await _carService.Get(id));
        }
        
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]Car model)
        {
            await _carService.Remove(model.Id);
            
            return RedirectToAction("Index");
        }
    }
}

CarWebApp/Views/Car/Create.cshtml
@model CarWebApp.Entities.Car

@{
    ViewData["Title"] = "Create";
}

<h1>Add new car</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VIN" class="control-label"></label>
                <input asp-for="VIN" class="form-control" />
                <span asp-validation-for="VIN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarModelId" class="control-label"></label>
                <select asp-for="CarModelId" class ="form-control" asp-items="ViewBag.CarModelId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarWebApp/Views/Car/DeleteConfirm.cshtml
@model CarWebApp.Entities.Car

@{
    ViewData["Title"] = "Delete Confirm";
}

<h1>Delete Confirm</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VIN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VIN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarModel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarModel.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Delete" class="btn btn-outline-danger"/>
        |
        <a asp-action="Index">
            <span class="btn btn-primary">Go Back</span>
        </a>
    </form>


</div>

CarWebApp/Views/Car/Edit.cshtml
@model CarWebApp.Entities.Car

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VIN" class="control-label"></label>
                <input asp-for="VIN" class="form-control" />
                <span asp-validation-for="VIN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarModelId" class="control-label"></label>
                <select asp-for="CarModelId" class="form-control" asp-items="ViewBag.CarModelId"></select>
                <span asp-validation-for="CarModelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarWebApp/Views/Car/List.cshtml
@using CarWebApp.Entities
@model CarListModel

@{
    ViewData["Title"] = "Index";
    var userRole = Context.Items["UserRole"] as UserRole?;

    List<SelectListItem> carBrands = ViewBag.CarBrands;
}


@using (Html.BeginForm("List", "Car", FormMethod.Get))
{
    <div class="d-flex justify-content-start">
        <input type="submit" value="Filter" class="btn btn-primary m-1 "/>
        @Html.DropDownList("CarBrandFilerId", carBrands, "All brands", new {@class = "form-control m-1 w-50"})
    </div>
}
<p class="float-right">
    @if (userRole == UserRole.Admin)
    {
        <a asp-action="Create">
            <button class="btn btn-primary m-1">Add new</button>
        </a>
    }
    <a href='@Url.Action("Print", "Car", new {carBrandFilerId = Model.CarBrandFilerId})'>
        <button class="btn btn-primary m-1">Print View</button>
    </a>
</p>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cars.FirstOrDefault().RegistrationNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cars.FirstOrDefault().VIN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cars.FirstOrDefault().CarModel.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cars.FirstOrDefault().CarModel.CarBrand.Name)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Cars)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VIN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarModel.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarModel.CarBrand.Name)
            </td>
            <td class="d-flex flex-row justify-content-center">
                @if (userRole is UserRole.Admin)
                {
                    <a asp-action="Edit" asp-route-id="@item.Id">
                        <button class="btn btn-primary m-1">Edit</button>
                    </a>
                    <a asp-action="DeleteConfirm" asp-route-id="@item.Id">
                        <button class="btn btn-danger m-1">Delete</button>
                    </a>
                }
            </td>
        </tr>
    }
    </tbody>
</table>

CarWebApp/Views/Car/PrintList.cshtml
@using CarWebApp.Entities
@model IEnumerable<Car>

@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VIN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarModel.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarModel.CarBrand.Name)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VIN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarModel.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarModel.CarBrand.Name)
            </td>
        </tr>
    }
    </tbody>
</table>